In [44]:
import numpy as np
import pandas as pd

In [2]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [12]:
array2=np.array([[
                [1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                [13,14,15],
                [16,17,18]]])
array2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
array1.shape(),array2.shape()

TypeError: 'tuple' object is not callable

In [14]:
array1.shape


(3,)

In [15]:
array2.shape

(2, 3, 3)

In [16]:
import pandas as pd


In [23]:
dframe=pd.DataFrame(array1)
dframe

0
0  1
1  2
2  3

In [25]:
dframe=pd.DataFrame(array1)
dframe

0
0  1
1  2
2  3

In [27]:
r=np.random.randint(0,10.2)

In [28]:
r


0

In [37]:
r=np.random.randint(0,20,size=(4,3))
r

array([[15,  3,  4],
       [11, 13, 16],
       [ 8, 11,  8],
       [18,  1,  0]])

In [36]:
r=np.random.random((4,3))
r

array([[0.40558922, 0.58365528, 0.13665861],
       [0.97310109, 0.09311853, 0.63289595],
       [0.26734896, 0.92278083, 0.69959887],
       [0.82666904, 0.79598354, 0.86254551]])

In [38]:
np.unique(r)

array([ 0,  1,  3,  4,  8, 11, 13, 15, 16, 18])

#butter bussiness example

In [43]:
np.random.seed(0)
ar=np.random.randint(3,15,size=(5,3))
ar

array([[ 8,  3,  6],
       [14,  6, 10],
       [12,  6,  8],
       [ 5,  7, 10],
       [ 9, 11, 11]])

In [61]:
frame=pd.DataFrame(ar,index=["mon","tue","wed","thurs","fri"],columns=["almond","peanut","cashew"])
frame

almond  peanut  cashew
mon         8       3       6
tue        14       6      10
wed        12       6       8
thurs       5       7      10
fri         9      11      11

In [52]:
price=np.array([10,8,12])
price

array([10,  8, 12])

In [53]:
price.shape

(3,)

In [54]:
price.T


array([10,  8, 12])

In [55]:
price.reshape(3,1)

array([[10],
       [ 8],
       [12]])

In [56]:
price


array([10,  8, 12])

In [63]:
prices=pd.DataFrame(price.reshape(1,3),index=["price"],columns=["almond","peanut","cashew"])
prices

almond  peanut  cashew
price      10       8      12

In [67]:
frame.dot(price.reshape(3,1))

0
mon    176
tue    308
wed    264
thurs  226
fri    310